thrain = Human("thrain","blond","grey",4,184,70,"male","dwarven","")
thrain.introduceSelf()
thrain.discribeSelf()
thrain.turn(input("enter a direction"))
print("\n\n")
ulag = Human("ulag","black","black",7,230,63,"male","orcish","")
ulag.introduceSelf()
ulag.discribeSelf()
ulag.turn(input())
print("\n\n")
lunalias = Human("lunalias","silver","bright blue",6,140,87,"female","elvish","")
lunalias.introduceSelf()
lunalias.discribeSelf()
lunalias.turn(input())